name: talk_fo_me
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    # 阿里云sdk
  #  ali_auth: ^1.2.7
  ali_auth:
    path: ./plugins/ali_auth
  cupertino_icons: ^1.0.6
  flutter_easyloading: 3.0.5
  fluttertoast: 8.2.5
  get: 4.6.6
  cached_network_image: 3.3.1
  flutter_cache_manager: 3.3.2
  dio: 5.4.3+1 #网络请求
  photo_view: 0.15.0 #画廊
  flutter_staggered_grid_view: 0.7.0 #瀑布流
  flutter_pickers: 2.1.9 #城市选择
  flutter_slidable: 3.1.0 #滑动删除
  image_picker: 1.1.1 #相机拍照
  lunar: 1.7.0 #日历：包含农历/阳历
  webview_flutter: 4.8.0 #webview
  permission_handler: 11.3.1 #权限管理
  common_utils: 2.1.0 #通用库
  image_gallery_saver: 2.0.3 #保存图片到图库
  shared_preferences: 2.2.3 #本地缓存
  package_info_plus: 8.0.0 #包管理
  system_clock: 2.0.0
  connectivity_plus: 6.0.3
  web_socket_channel: 3.0.0
  pretty_dio_logger: 1.3.1
  logger: 2.3.0
  dotted_border: 2.1.0
  soundpool: 2.4.1
  pull_to_refresh: ^2.0.0
  infinite_scroll_pagination: ^4.0.0
  flutter_swiper_null_safety: ^1.0.2 #轮播

  scrollview_observer: ^1.20.0 # 滚动定位
  svgaplayer_flutter: ^2.2.0

  crypto: ^3.0.3 # 加密
  intl: 0.18.1
  auto_size_text: 3.0.0
  fading_edge_scrollview: ^4.1.1
  just_audio: ^0.9.38 # 音频播放
  path_provider: ^2.1.3
  path: 1.9.0
  collection: 1.18.0 # 集合扩展库
  sqflite: ^2.3.3+1 # 数据库
  wechat_kit: ^6.0.1
  url_launcher: ^6.3.0
  lrc: ^1.0.2
  audio_video_progress_bar: ^2.0.3
  google_fonts: ^6.2.1 #谷歌字体
  sensors_plus: ^5.0.1
  visibility_detector: ^0.4.0+2
  sign_in_with_apple: ^6.1.1
  device_info_plus: ^10.1.0
  in_app_purchase: ^3.2.0
  uuid: ^4.0.0

  getuiflut: 0.2.29 # 个推推送
  extended_image: ^8.2.1
  image_editor: ^1.5.1

dependency_overrides:
  http: ^1.2.1 # svgaplayer_flutter 和 flutter_cache_manager会冲突，强制使用flutter_cache_manager依赖版本
  webview_flutter_android: 3.16.1

wechat_kit:
  ios: no_pay
  app_id: wx11c2ff36e713482b
  universal_link: https://jxapi.jingxiu88.com/app/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/common/
    - assets/images/home/
    - assets/images/disambiguation/
    - assets/images/mine/
    - assets/images/wish_pavilion/
    - assets/images/wish_pavilion/zen_room/
    - assets/images/wish_pavilion/homesick/
    - assets/images/wish_pavilion/charm/
    - assets/images/plaza/
    - assets/images/login/
    - assets/audio/
    - assets/svga/
    - assets/js/
    - assets/textures/
    #   - images/a_dot_ham.jpeg
  fonts:
    - family: NotoSerifSC
      fonts:
        - asset: assets/fonts/NotoSerifSC-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSerifSC-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSerifSC-Bold.ttf
          weight: 700
    - family: BEBAS
      fonts:
        - asset: assets/fonts/BEBAS.ttf

flutter_intl:
  enabled: true
  main_locale: zh
